INSERT INTO tutu_stations(station_id,station_name) VALUES (2060533,'Агрыз');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064150,'Адлер');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064188,'Анапа');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004717,'Апатиты-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060320,'Арзамас Город');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060396,'Арзамас-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060390,'Арзамас-2');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064240,'Армавир Ростовский');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064290,'Армавир Туапсинский');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010441,'Архангельск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010400,'Архангельск Город');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2020600,'Астрахань');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2020865,'Балаково');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014370,'Белгород');
INSERT INTO tutu_stations(station_id,station_name) VALUES (8010100,'Берлин Главный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (8010111,'Берлин Лихтенберг');
INSERT INTO tutu_stations(station_id,station_name) VALUES (8010110,'Берлин Остбанхоф');
INSERT INTO tutu_stations(station_id,station_name) VALUES (5900001,'Бишкек');
INSERT INTO tutu_stations(station_id,station_name) VALUES (5900898,'Бишкек-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (5900000,'Бишкек-2');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2004660,'Бологое-Московское');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2100035,'Брест-Центральный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000427,'Брянск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000420,'Брянск-Льговский');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000160,'Брянск-Орловский');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2004540,'Великие Луки');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004400,'Великий Новгород (Новгород-на-Волхове)');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2400000,'Вильнюс');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2400001,'Вильнюс Центр');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060340,'Владимир');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2020500,'Волгоград-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010041,'Вологда');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010030,'Вологда-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014000,'Воронеж');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014001,'Воронеж-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004460,'Вышний Волочёк');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000830,'Вязьма');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060365,'Вятские Поляны');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060530,'Глазов');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2100100,'Гомель-Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2100070,'Гродно');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060420,'Дзержинск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024683,'Димитровград');
INSERT INTO tutu_stations(station_id,station_name) VALUES (6600000,'Душанбе-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064040,'Ейск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030000,'Екатеринбург Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010130,'Иваново');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060150,'Ижевск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2054000,'Иркутск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2054001,'Иркутск Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2054002,'Иркутск Сортировочный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060593,'Йошкар-Ола');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2060615,'Казань');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060500,'Казань Пасс');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060961,'Казань-2 (Восстание Пасс.)');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000345,'Калуга-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000350,'Калуга-2');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060630,'Канаш-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004715,'Кандалакша');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060600,'Киров Пасс');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060006,'Киров-Котласский');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2300000,'Кишинэу');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2300001,'Кишинэу Центр');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2001021,'Клинцы');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060350,'Ковров-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024540,'Ковылкино');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010090,'Кострома-Новая');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064788,'Краснодар');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064800,'Краснодар-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000150,'Курск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064030,'Лазаревская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014130,'Липецк');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014120,'Лиски');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000310,'Льгов-1-Киевский');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2100000,'Минск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2100001,'Минск-Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2100150,'Могилев-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2200280,'Могилев-Подольский');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000000,'Москва');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000006,'Москва Белорусская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000003,'Москва Казанская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000007,'Москва Киевская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000001,'Москва Курская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2006004,'Москва Октябрьская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000005,'Москва Павелецкая');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000008,'Москва Рижская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000009,'Москва Савёловская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000002,'Москва Ярославская');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2004200,'Мурманск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060370,'Муром-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024525,'Набережные Челны');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030308,'Нижневартовск-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060001,'Нижний Новгород Моск.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (8700400,'Ницца');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064110,'Новороссийск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030319,'Новый Уренгой');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030526,'Нягань');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2044700,'Омск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2040210,'Оренбург');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000140,'Орёл');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2040480,'Орск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (8700012,'Париж Восточный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024120,'Пенза-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004300,'Петрозаводск-Пасс');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030400,'Пермь-2');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2100190,'Полоцк');
INSERT INTO tutu_stations(station_id,station_name) VALUES (5457076,'Прага Главный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030607,'Пыть-Ях');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2500001,'Рига-Пасажиеру');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024550,'Рузаевка');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014540,'Россошь');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2064000,'Ростов');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064001,'Ростов-Главный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010226,'Ростов-Ярославский');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014720,'Ртищево-1');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2000125,'Рязань (все вокзалы)');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000120,'Рязань-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000080,'Рязань-2');

INSERT INTO tutu_stations(station_id,station_name) VALUES (2024000,'Самара');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004000,'Санкт-Петербург');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004006,'Санкт-Петербург Ладож.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004005,'Санкт-Петербург-Балт.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004003,'Санкт-Петербург-Витеб.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004001,'Санкт-Петербург-Главн.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004004,'Санкт-Петербург-Финл.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024700,'Саранск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2020000,'Саратов-1 Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000190,'Сасово');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060410,'Сергач');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000170,'Смоленск Центральный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030600,'Сургут');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064130,'Сочи');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014340,'Старый Оскол');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024739,'Сызрань');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024602,'Сызрань Город');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024610,'Сызрань-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2600000,'Таллин');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2600001,'Таллин Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2014700,'Тамбов-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2900000,'Ташкент');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2900001,'Ташкент Пасс Центр.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2900002,'Ташкент Южный');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2004600,'Тверь');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024810,'Тольятти');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2064140,'Туапсе-Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000174,'Тула');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000880,'Тула-1-Курская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000173,'Тула-3-Вяземская');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2030100,'Тюмень');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024900,'Ульяновск Центр.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2000430,'Унеча');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2024600,'Уфа');
INSERT INTO tutu_stations(station_id,station_name) VALUES (1000001,'Хельсинки');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060620,'Чебоксары');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2040000,'Челябинск');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010290,'Череповец-1');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060431,'Шумерля');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2060542,'Янаул');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010000,'Ярославль');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010002,'Ярославль Пасс.');
INSERT INTO tutu_stations(station_id,station_name) VALUES (2010001,'Ярославль-Главный');


